Vagrant.configure('2') do |config|
    config.vm.box = 'ubuntu/focal64'
    config.disksize.size = '100GB'
    config.vm.host_name = 'vagruntu-focal'
  
    config.vm.provider 'virtualbox' do |vb|
      vb.gui = false
      vb.cpus = 8
      vb.memory = 16384
      vb.name = 'vagruntu-focal'
    end
  
    config.vm.provision 'shell', path: './provision.sh'
  end
  