Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'
  # config.vm.box = 'bento/ubuntu-20.04'
  config.disksize.size = '100GB'
  config.vm.host_name = 'vagruntu-focal'
  config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2200

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.cpus = 8
    vb.memory = 16_384
    vb.name = 'vagruntu-focal'
  end

  config.vm.provision 'shell', path: './provision/base.sh'
end
