Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/focal64'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
  end

  config.vm.provision 'shell', path: './provision.sh', privileged: false
end
